config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trips, only: [:new, :create, :show, :index] do
    resources :bookings, only: [:create]
  end
  resources :reservations, only: [] do
    member do
      patch 'accept'
      patch 'deny'
    end
  end
  resource :profile, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to  :user
  belongs_to  :trip

end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :captain, class_name: 'User'
  has_many :users, through: :bookings
  has_many :bookings
  mount_uploader :photo, PhotoUploader

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many  :bookings
  has_many  :trips, foreign_key: 'captain_id'
  mount_uploader :profile_pic, ProfilePicUploader

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :profile_pic, :profile_pic_cache])

    # # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_trip, only: [:create]
  before_action :authenticate_user!, only: [:create]
  
  def create
    @booking = Booking.new(booking_params)
    @booking.trip = @trip

    if @booking.save
      redirect_to trip_path(@trip)
      flash[:notice] = "You've booked your trip !"
    else
      flash[:alert] = "Booking failed"
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:user_id, :price, :first_name, :last_name, :trip_id, :motivation)
  end


  def set_trip
    @trip = Trip.find(params[:trip_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @trips = Trip.all
    @cards = @trips.sample(3)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @trips = current_user.trips
    @bookings = current_user.bookings.sort
    @captain_bookings = []

    Booking.all.each do |booking|
      @captain_bookings << booking if booking.trip.captain == current_user
    end
    @captain_bookings.sort
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_booking
  before_action :authenticate_user!

  def accept
    @booking.update(:status => "Accepted")
    if @booking.save
      redirect_to profile_path(current_user)
      flash[:notice] = "Booking successfully accepted!"
    else
      flash[:alert] = "Booking confirmation failed"
    end
  end

  def deny
    @booking.update(:status => "Deny")
    if @booking.save
      redirect_to profile_path(current_user)
      flash[:notice] = "Booking successfully denied!"
    else
      flash[:alert] = "Booking confirmation failed"
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_trip, only: [:show]

  def index
    @trips = if params[:departure_date] == ""
      Trip.where('departure_port LIKE ?', "%#{params[:departure_port]}%")
    elsif params[:departure_port] && params[:departure_date]
      Trip.where('departure_port LIKE ? AND departure_date = ?', "%#{params[:departure_port]}%", params[:departure_date])
    else
      Trip.all
    end
  end

  def show
    @booking = Booking.new
    @bookings = @trip.bookings.count
    @remaining_places = @trip.capacity - @bookings
    if current_user
      current_user.bookings.each do |booking|
        @user_booking = booking if booking.trip_id == @trip.id
      end
    end

  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.create(trip_params)
    @trip.captain = current_user

    if @trip.save
      redirect_to trip_path(@trip)
      flash[:notice] = "You've added your trip !"
    else
      flash[:alert] = "Trip creation failed"
    end
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:departure_port, :arrival_port, :departure_date, :duration, :distance, :boat_name, :description, :capacity, :price, :captain_id, :photo)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar_url(user)
    return user.facebook_picture_url || user.profile_pic
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AirSails</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background: linear-gradient(-350deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), no-repeat center center fixed url('<%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1>Welcome to AirSails</h1>
    <p>Unique sailing trip</p>
    <%= form_tag trips_path, method: :get do %>
    <%= text_field_tag :departure_port, nil, placeholder: "Choose a port", class: "btn-lg search" %>
    <%= text_field_tag :departure_date, nil, placeholder: "Date", class: "datepicker btn-lg search", "data-date-start-date": "+1d" %>
    <%= submit_tag "Search", class:"btn btn-primary btn-lg" %>
    <% end %>
    <div class="container">
      <div class="actiontrip">
        <%= link_to "Voir tous les voyages", trips_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h1 class="text-center">Drop the moorings</h1>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <p align="center"><%= image_tag "globe.png", alt: "Globe" %></p>
    <h2 class="text-center">Discovery</h2>
    <p class="text-center">Discover the world only by the force of the wind.</p>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <p align="center"><%= image_tag "beer.png", alt: "Beer" %></p>
    <h2 class="text-center">Lifestyle</h2>
    <p class="text-center">Meet the ocean's way of life.</p>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <p align="center"><%= image_tag "dollar.png", alt: "Dollar" %></p>
    <h2 class="text-center">Affordable</h2>
    <p class="text-center">You have the wind in your sails.</p>
  </div>
</div>

<div class="wrapper">
  <div class="container">
    <h1 class="text-center">Travel offers</h1>
  <div class="row">
    <% @cards.each do |trip| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0, 0.2)), url('<%= trip.photo.url(:standard) %>');">
        <div class="card-category"> <%= trip.departure_port %> <i class="fa fa-arrows-h" aria-hidden="true"></i> <%= trip.arrival_port %> </div>
        <div class="card-description">
          <h2><%= trip.boat_name %></h2>
          <p><%= trip.description %></p>
        </div>
        <img class="card-user avatar avatar-large" src="<%= image_path trip.captain.profile_pic  %>">
        <%= link_to 'voir', trip_path(trip), class: 'card-link' %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>


<%= content_for(:after_js) do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker({
        todayHighlight: true,
        autoclose: true,
        startDate: '-0d'
      });
    });
  </script>
<% end %>

app/views/profiles/show.html.erb
<div class="col-md-12">
  <h1 class="text-center">Welcome</h1>
  <h3 class="text-center"><%= current_user.first_name %></h3>
</div>
<div class="avatar-profile">
  <img src="<%= current_user.profile_pic %>" alt="user" class="avatar-profile-large">
</div>
<div class="col-lg-12">
  <div class="info">
    <h3 class="text-center">Info</h3>
      <p class="text-center">Last Name : <%= current_user.last_name %></p>
      <p class="text-center">First Name : <%= current_user.first_name %></p>
      <p class="text-center">E-mail : <%= current_user.email %></p>
  </div>
</div>


  <div class="container">
    <h3 class="text-center">Reservation for my trips</h3>
        <% if @captain_bookings == [] %>
        <p class="text-center padded"> No reservations yet ! </p>
        <% else %>
        <% @captain_bookings.each do |booking| %>
        <div class="product">
        <ul class="list-inline product-controls col-lg-offset-2">
        <li><%= image_tag "holidays.png" %></li>
        <li><%= booking.user.first_name %> booked a place on your trip !</li>
        <li><strong>Motivation</strong> : <%= booking.motivation %></li>
        <li><strong>Status</strong> : <%= booking.status %></li>
        <li><%= link_to "Accept", accept_reservation_path(booking), method: :patch, data: {confirm: "Are you sure?"}, class: "btn btn btn-success"  %></li>
        <li><%= link_to "Deny", deny_reservation_path(booking), method: :patch, data: {confirm: "Are you sure?"}, class: "btn btn btn-danger"  %></li>
        </ul>
        </div>
        <% end %>
        <% end %>
  </div>




<div class="container">
  <h3 class="text-center">My trips reserved</h3>
      <% if @bookings == [] %>
      <p class="text-center padded"> No trips reserved yet ! </p>
      <% else %>
      <% @bookings.each do |booking| %>
      <div class="product">
      <ul class="list-inline product-controls col-lg-offset-2">
      <li><%= image_tag "transport.png" %></li>
      <li><strong><%= booking.trip.departure_port %></strong><i class="fa fa-arrows-h" aria-hidden="true"></i><strong> <%= booking.trip.arrival_port %></strong></li>
      <li><%= link_to "View trip details !", trip_path(booking.trip), class: "text-center btn btn-success", target: "_blank" %></li>
      <li>Status : <%= booking.status %></li>
      </ul>
      </div>
  <% end %>
  <% end %>
</div>

app/views/reservations/index.html.erb
@bookings

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-instagram"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <p>This is an AirSails project @ LeWagon</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="container">

  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Booking confirmation</h4>
        </div>
        <div class="modal-body">
          <h3> Your informations : </h3>
          <ul>
            <li>Name : <%= current_user.first_name %> <%= current_user.last_name %></li>
            <li>Email : <%= current_user.email %></li>
            <li>Phone number : <%= current_user.phone_number %></li>
          </ul>
          <h4>Would you like to book a trip for yourself ?</h4>

          <%= simple_form_for [@trip, @booking] do |f| %>
          <%=f.hidden_field :user_id, :value => current_user.id %>
          <%=f.hidden_field :first_name, :value => current_user.first_name %>
          <%=f.hidden_field :last_name, :value => current_user.last_name %>
          <%=f.hidden_field :trip_id, :value => @trip.id %>
          <%=f.hidden_field :price, :value => @trip.price %>
          <%= f.submit class: "btn btn-danger", style: "width: 100%", value: "Book for myself" %>
          <% end %>
        </div>
        <div class="modal-body">
          <h4>Would you like to book a trip for someone else ?</h4>
          <h5>(You won't have to create an account, just specify the name)</h5>
          <%= simple_form_for [@trip, @booking] do |f| %>
          <%=f.hidden_field :user_id, :value => current_user.id %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%=f.hidden_field :trip_id, :value => @trip.id %>
          <%=f.hidden_field :price, :value => @trip.price %>
          <%= f.submit class: "btn btn-danger", style: "width: 100%", value: "Book for this person" %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_booking.html.erb
<div class="container">
  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Booking confirmation</h4>
        </div>
        <div class="modal-body">
          <h4>Would you like to book a trip for yourself ?</h4>

          <%= simple_form_for [@trip, @booking] do |f| %>
          <%=f.hidden_field :user_id, :value => current_user.id %>
          <%=f.hidden_field :first_name, :value => current_user.first_name %>
          <%=f.hidden_field :last_name, :value => current_user.last_name %>
          <%=f.hidden_field :trip_id, :value => @trip.id %>
          <%=f.hidden_field :price, :value => @trip.price %>
          <%= f.input :motivation, required: true, placeholder: "Your motivation in a few words" %>
          <%= f.submit class: "navbar-wagon-item navbar-wagon-button btn", style: "width: 100%", value: "Book for myself" %>
          <% end %>
        </div>
        <div class="modal-body">
          <h4>Would you like to book a trip for someone else ?</h4>
          <h5>(You won't have to create an account, just specify the name)</h5>
          <%= simple_form_for [@trip, @booking] do |f| %>
          <%=f.hidden_field :user_id, :value => current_user.id %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :motivation, required: true, placeholder: "Your motivation in a few words" %>
          <%=f.hidden_field :trip_id, :value => @trip.id %>
          <%=f.hidden_field :price, :value => @trip.price %>
          <%= f.submit class: "navbar-wagon-item navbar-wagon-button btn", style: "width: 100%", value: "Book for this person" %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_impossible.html.erb
<div class="container">

  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <div class="text-center">
          <h3> Sorry, this trip is full ! </h3>
          <p>Try another trip, or maybe try this one later !</p>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_login.html.erb
<div class="container">

  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <div class="text-center">
          <h3> You must be logged in to book a trip ! </h3>
          <br>

            <%= link_to "I already have an account !", new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
            <%= link_to "I don't have an account...", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Notification -->
    <!-- <%= link_to "#", class: "navbar-wagon-item navbar-wagon-button btn" do %>
    <div class="badge-container">
      <i class="fa fa-envelope-o"></i>
      <div class="badge badge-blue">3</div>
    </div>
    <% end %> -->

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag user_avatar_url(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "/" do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Create a trip"), new_trip_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <h1>Croisières disponibles</h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row padded">
    <% @trips.each do |trip| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= trip.photo.url(:standard) %>');">
        <div class="card-category"> <%= trip.departure_port %> <i class="fa fa-arrows-h" aria-hidden="true"></i> <%= trip.arrival_port %> </div>
        <div class="card-description">
          <h2><%= trip.boat_name %></h2>
          <p><%= trip.description %></p>
        </div>
        <img class="card-user avatar avatar-large" src="<%= image_path trip.captain.profile_pic %>">
        <%= link_to 'voir', trip_path(trip), class: 'card-link' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/trips/new.html.erb
<h1 class="text-center">Create a trip</h2>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-center">
      <%= simple_form_for(@trip) do |f| %>
      <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :departure_port, required: true, autofocus: true %>
    <%= f.input :arrival_port, required: true, autofocus: true %>
    <%= f.input :departure_date, required: true %>
    <%= f.input :duration, required: true, autofocus: true %>
    <%= f.input :distance, required: true, autofocus: true %>
    <%= f.input :boat_name, required: true, autofocus: true %>
    <%= f.input :capacity, required: true, autofocus: true %>
    <%= f.input :price, required: true, autofocus: true %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>


      <div class="form-actions">
        <%= f.button :submit, "Create your trip", class: "btn btn-primary btn-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<% if @remaining_places == 0 %>
<%= render 'shared/modal_impossible' %>
<% else %>
<% if current_user %>
<%= render 'shared/modal_booking' %>
<% else %>
<%= render 'shared/modal_login' %>
<% end %>
<% end %>


<div class="boat-pic" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 50%), url(<%= @trip.photo.url(:standard) %>)">
  <div class="header-trip">
    <div class="header-trip-captain text-center padded">
      <%= image_tag @trip.captain.profile_pic, class: "avatar-mega-large avatar-circle" %>
      <p><%= @trip.captain.first_name %></p>
    </div>
    <div>
      <h1>
        <%= @trip.departure_port %><i class="fa fa-arrow-right"></i><%= @trip.arrival_port %>
      </h1>
      <p><%= @trip.description %></p>
      <p>Price: <strong><%=@trip.price%> <i class="fa fa-eur"></i></strong></p>
      <p>Remaining places: <%= @remaining_places %> </p>
    </div>
    <button type="button" class="navbar-wagon-item navbar-wagon-button btn book-trip" data-toggle="modal" data-target="#myModal">
      Book this trip
    </button>
    <!-- <form action="/trips/<%=@trip.id%>/bookings" method="post" data= { confirm: 'Are you sure?' } >
    <h4><i class="fa fa-star" style="color: #ffb400"></i> Book from <%=@trip.price%> €</h4>
    <input type="submit" class="btn btn-danger" value="Book this trip" style="width: 100%">
  </form> -->
</div>
</div>

<div class="trip-description">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12">
        <div class="row" id="trip-data">
          <div class="col-xs-12 col-sm-2">
            <strong><h5><u><FONT size="4pt">About the trip:</font></h5></u></strong>
            </div>
            <div class="col-xs-12 col-sm-4">
              <ul class="list-unstyled">
                <li>Departure port:  <strong><%= @trip.departure_port %></strong></li>
                <li>Arrival port:  <strong><%= @trip.arrival_port %></strong></li>
                <li>Departure date:  <strong><%= @trip.departure_date %></strong></li>
                <li>Distance (in nautical miles):  <strong><%= @trip.distance %> nm</strong></li>
                <li>Estimated duration:  <strong><%= @trip.duration %> days</strong></li>
                <% if @user_booking == nil %>
                <% else %>
                  <% if @user_booking.status == "Accepted" %>
                  <li><%= "Contact:" %></li>
                  <li><i class="fa fa-envelope"></i><%= @trip.captain.email %></li>
                  <li><i class="fa fa-phone"></i><%= @trip.captain.phone_number %></li>
                <% end %>
                <% end %>
              </ul>
            </div>

            <div class="col-xs-12 col-sm-2">
              <strong><u><h5><FONT size="4pt">About the boat:</font></h5></strong></u>
              </div>
              <div class="col-xs-12 col-sm-4">
                <ul class="list-unstyled">
                  <li><i class="fa fa-user-circle-o"></i><strong><%=@trip.captain.first_name%> <%=@trip.captain.last_name%></strong></li>
                  <li><i class="fa fa-ship"></i><strong><%=@trip.boat_name%></strong></li>
                  <li><i class="fa fa-info-circle"></i><strong><%=@trip.description%></strong></li>
                  <li><i class="fa fa-users"></i><strong><%=@trip.capacity%> peoples</strong></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>